spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gaoxiang?characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: gaoxiang
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


